theme = "blowfish"
baseURL = "https://roethof.net/"

timeZone = "Europe/Amsterdam"
defaultContentLanguage = "en"
languageCode = "en-us"
timeout = "180s"

enableGitInfo = true
enableRobotsTXT = true
summaryLength = 0

buildDrafts = false
buildFuture = true

enableEmoji = true

googleAnalytics = "G-CZKZHB3R90"

[pagination]
  pagerSize = 100

[imaging]
  anchor = 'Center'

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"

[sitemap]
  changefreq = 'weekly'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON", "htaccess", "humanstxt", "txt"]

[outputFormats]
[outputFormats.htaccess]
    baseName = ""
    isPlainText = true
    mediaType = "text/htaccess"

[outputFormats.humanstxt]
    baseName = "humans"
    isPlainText = true
    mediaType = "text/plain"

[outputFormats.txt]
    isPlainText = true
    mediaType = "text/plain"

[mediaTypes]
  [mediaTypes."text/htaccess"]
    suffixes = ["htaccess"]

[related]
  threshold = 0
  toLower = false

    [[related.indices]]
        name = "tags"
        weight = 100

    [[related.indices]]
        name = "categories"
        weight = 100

    [[related.indices]]
        name = "series"
        weight = 50

    [[related.indices]]
        name = "authors"
        weight = 20

    [[related.indices]]
        name = "date"
        weight = 10

    [[related.indices]]
      applyFilter = false
      name = 'fragmentrefs'
      type = 'fragments'
      weight = 10
