# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  pre = "briefcase"
  name = "Categories"
  weight = 10
  url = "/categories"

[[main]]
  name = "Tutorials"
  parent = "Categories"
  weight = 11
  url = "/categories/tutorials"

[[main]]
  name = "Arch Linux"
  parent = "Categories"
  weight = 12
  url = "/categories/arch-linux"

[[main]]
  name = "Security"
  parent = "Categories"
  weight = 13
  url = "/categories/security"

[[main]]
  name = "Tips"
  parent = "Categories"
  weight = 14
  url = "/categories/tips"
  
[[main]]
  pre = "briefcase"
  name = "Resume"
  url = "https://ronnyroethof.nl"
  weight = 20

[[main]]
  name = "Links"
  url = "https://familieroethof.nl"
  weight = 30

[[main]]
  pre = "heart"
  name = "Partner"
  weight = 40
  url = "/partner"

[[main]]
  name              = "Subscribe via RSS"
  identifier        = "subscribe"
  url               = "https://roethof.net/index.xml"
  weight = 50

[[main]]
  identifier = "linkedin"
  pre = "linkedin"
  url = "https://www.linkedin.com/in/rroethof/" 
  weight = 60

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/rroethof"
  weight = 70

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

[[footer]]
  name = "Partner"
  url = "/partner"
  weight = 10

[[footer]]
  name = "Privacy"
  url = "/privacy"
  weight = 30

[[footer]]
  name = "Security"
  pageRef = "security"
  weight = 40
[[footer]]
  name              = "RSS"
  identifier        = "subscribe"
  url               = "https://roethof.net/index.xml"
  weight = 20