# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  pre = "list"
  name = "Categories"
  weight = 10
  url = "/categories/"

[[main]]
  pre = "cloud-music"
  name = "Music"
  weight = 11
  url = "/music/"

[[main]]
  pre = "address-card"
  name = "About"
  pageRef = "about"
  weight = 15

[[main]]
  pre = "briefcase"
  name = "Resume"
  url = "https://ronnyroethof.nl"
  weight = 20

[[main]]
  pre = "heart"
  name = "Partner"
  weight = 40
  pageRef = "partner"

[[main]]
  pre = "lock"
  name = "GPG"
  weight = 50
  pageRef = "gpg"


[[main]]
  identifier = "rss"
  pre = "rss"
  url = "https://roethof.net/index.xml"
  weight = 60

[[main]]
  identifier = "linkedin"
  pre = "linkedin"
  url = "https://www.linkedin.com/in/rroethof/" 
  weight = 70

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/rroethof"
  weight = 80

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

[[footer]]
  name              = "Partner"
  pageRef           = "partner"
  weight            = 10

[[footer]]
  name              = "About"
  pageRef           = "about"
  weight            = 20

[[footer]]
  name              = "GPG"
  pageRef           = "gpg"
  weight            = 30

[[footer]]
  name              = "RSS"
  identifier        = "Subscribe"
  url               = "https://roethof.net/index.xml"
  weight            = 40

[[footer]]
  name              = "Privacy"
  pageRef           = "privacy"
  weight            = 50

[[footer]]
  name              = "Security"
  pageRef           = "security"
  weight            = 60

